### ISSUE TITLE
When I reproduced TR3D, there was a problem that I could not understand. Is there any solution to this problem

### ISSUE THREAD

**Issue by Wang0526** [SamsungLabs/tr3d#2]
Problems encountered：

(det3d) a113@a113-Default-string-Invalid-entry-length-16-Fixed-up-to-11:~/桌面/TR3D$ python tools/test.py configs/tr3d/tr3d_sunrgbd-3d-10class.py  weights/tr3d_sunrgbd.pth --eval mAP --show  --show-dir weights/test
/home/a113/anaconda3/envs/det3d/lib/python3.8/site-packages/mmdet/utils/setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/a113/anaconda3/envs/det3d/lib/python3.8/site-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "/home/a113/anaconda3/envs/det3d/lib/python3.8/site-packages/mmcv/utils/registry.py", line 71, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'neck'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 260, in <module>
    main()
  File "tools/test.py", line 208, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/a113/mmdetection3d/mmdet3d/models/builder.py", line 132, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/a113/mmdetection3d/mmdet3d/models/builder.py", line 102, in build_detector
    return DETECTORS.build(
  File "/home/a113/anaconda3/envs/det3d/lib/python3.8/site-packages/mmcv/utils/registry.py", line 239, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/a113/anaconda3/envs/det3d/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/a113/anaconda3/envs/det3d/lib/python3.8/site-packages/mmcv/utils/registry.py", line 74, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MinkSingleStage3DDetector: __init__() got an unexpected keyword argument 'neck'

**Comment by Wang0526** [comment]
> According to your log ` "/home/a113/mmdetection3d/mmdet3d/models/builder.py"` looks like you have installed mmdetection3d? You don't need to do it, as `tr3d/mmdet3d` should be used here.

It's no issue when i following your method, thank you
