### ISSUE TITLE
KeyError: 'MinkSingleStage3DDetector is not in the models registry'

### ISSUE THREAD

**Issue by zw1765** [SamsungLabs/tr3d#7]
Training configuration file error requires your help:
KeyError: 'MinkSingleStage3DDetector is not in the models registry'

**Comment by zw1765** [comment]
python tools/train.py configs/tr3d/tr3d_sunrgbd-3d-10class.py 

Traceback (most recent call last):
  File "tools/train.py", line 262, in <module>
    main()
  File "tools/train.py", line 221, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/zw/anaconda3/envs/tr3d/lib/python3.7/site-packages/mmdet3d/models/builder.py", line 122, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/zw/anaconda3/envs/tr3d/lib/python3.7/site-packages/mmdet3d/models/builder.py", line 96, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zw/anaconda3/envs/tr3d/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/zw/anaconda3/envs/tr3d/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zw/anaconda3/envs/tr3d/lib/python3.7/site-packages/mmcv/utils/registry.py", line 62, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'MinkSingleStage3DDetector is not in the models registr

**Comment by zw1765** [comment]
Thank you for your reply. I have already solved this problem. thank you

**Comment by zw1765** [comment]
> For some reason I don't see your error traceback on github, however it is presented in the email notification...
> 
> ```
> File "/home/zw/anaconda3/envs/tr3d/lib/python3.7/site-packages/mmdet3d/models/builder.py", line 122, in build_model
> ```
> 
> This line probably means you installed separate `mmdetection3d` package. However you shouldn't do it as `mmdet3d` should be imported from `./mmdet3d` in the base folder of your `tr3d` project.

Thank you for your reply. I have already solved this problem. thank you
